'use client';

import { Lightbulb, RefreshCw } from 'lucide-react';
import { useState } from 'react';

import { formatAmount } from '@/lib/format';

type Insights = {
  overview: string;
  suggestions: {
    title: string;
    detail: string;
    estimatedMonthlySaving: number | null;
  }[];
  model: string;
};

export function InsightsPanel() {
  const [insights, setInsights] = useState<Insights | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch('/api/insights', { method: 'POST' });
      const body = await response.json().catch(() => null);
      if (!response.ok) {
        setError(body?.error ?? 'Failed to generate insights');
        return;
      }
      setInsights(body);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="rounded-lg border border-border bg-white p-6 shadow-sm dark:bg-slate-800">
      <div className="mb-4 flex items-center justify-between gap-4">
        <h2 className="text-lg font-semibold">Savings advice</h2>
        <button
          type="button"
          onClick={generate}
          disabled={loading}
          className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground transition hover:opacity-90 disabled:opacity-50"
        >
          <RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
          {loading ? 'Analyzing…' : insights ? 'Regenerate' : 'Get advice'}
        </button>
      </div>

      {error && <p className="text-sm text-red-600">{error}</p>}

      {!insights && !error && !loading && (
        <p className="text-sm text-muted-foreground">
          Ask the AI to analyze your spending cycle and suggest where you can save.
        </p>
      )}

      {insights && (
        <div className="space-y-4">
          <p className="text-sm leading-relaxed">{insights.overview}</p>
          <ul className="space-y-3">
            {insights.suggestions.map((suggestion) => (
              <li
                key={suggestion.title}
                className="rounded-md border border-border p-4"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex items-start gap-2">
                    <Lightbulb className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
                    <div>
                      <p className="text-sm font-semibold">{suggestion.title}</p>
                      <p className="mt-1 text-sm text-muted-foreground">
                        {suggestion.detail}
                      </p>
                    </div>
                  </div>
                  {suggestion.estimatedMonthlySaving != null && (
                    <span className="whitespace-nowrap text-sm font-semibold text-emerald-600">
                      ~{formatAmount(suggestion.estimatedMonthlySaving)}/mo
                    </span>
                  )}
                </div>
              </li>
            ))}
          </ul>
          <p className="text-xs text-muted-foreground">Generated by {insights.model}</p>
        </div>
      )}
    </div>
  );
}
