'use client';

import { Lightbulb, RefreshCw } from 'lucide-react';
import { useState } from 'react';

import { formatAmount } from '@/lib/format';

type Insights = {
  overview: string;
  suggestions: {
    title: string;
    detail: string;
    estimatedMonthlySaving: number | null;
  }[];
  model: string;
};

export function InsightsPanel() {
  const [insights, setInsights] = useState<Insights | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch('/api/insights', { method: 'POST' });
      const body = await response.json().catch(() => null);
      if (!response.ok) {
        setError(body?.error ?? 'Failed to generate insights');
        return;
      }
      setInsights(body);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="surface overflow-hidden">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/[0.06] px-5 py-5 sm:px-6">
        <div className="flex items-center gap-3">
          <span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-400/10 text-amber-400">
            <Lightbulb className="h-5 w-5" />
          </span>
          <div>
            <h2 className="text-base font-semibold text-slate-100">Your personalized plan</h2>
            <p className="mt-0.5 text-sm text-slate-500">Built from your recent spending</p>
          </div>
        </div>
        <button
          type="button"
          onClick={generate}
          disabled={loading}
          className="primary-button"
        >
          <RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
          {loading ? 'Analyzing…' : insights ? 'Regenerate' : 'Get advice'}
        </button>
      </div>

      <div className="p-5 sm:p-6">
        {error && (
          <div className="rounded-xl border border-rose-400/15 bg-rose-400/[0.07] px-4 py-3 text-sm text-rose-300">{error}</div>
        )}

        {!insights && !error && (
          <div className="grid min-h-56 place-items-center rounded-xl border border-dashed border-white/[0.09] bg-white/[0.02] px-6 py-10 text-center">
            <div>
              <SparkleMark />
              <p className="mt-4 font-medium text-slate-200">
                {loading ? 'Reviewing your spending…' : 'Turn your transactions into a plan'}
              </p>
              <p className="mx-auto mt-1.5 max-w-md text-sm leading-6 text-slate-500">
                {loading
                  ? 'This usually takes just a moment.'
                  : 'Ask the AI to spot patterns and suggest realistic ways to save each month.'}
              </p>
            </div>
          </div>
        )}

        {insights && (
          <div className="space-y-5">
            <p className="text-sm leading-7 text-slate-300">{insights.overview}</p>
            <ul className="space-y-3">
              {insights.suggestions.map((suggestion) => (
                <li
                  key={suggestion.title}
                  className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex items-start gap-2">
                      <Lightbulb className="mt-0.5 h-4 w-4 shrink-0 text-amber-400" />
                      <div>
                        <p className="text-sm font-semibold">{suggestion.title}</p>
                        <p className="mt-1 text-sm leading-6 text-slate-500">
                          {suggestion.detail}
                        </p>
                      </div>
                    </div>
                    {suggestion.estimatedMonthlySaving != null && (
                      <span className="whitespace-nowrap text-sm font-semibold text-emerald-400">
                        ~{formatAmount(suggestion.estimatedMonthlySaving)}/mo
                      </span>
                    )}
                  </div>
                </li>
              ))}
            </ul>
            <p className="text-xs text-slate-600">Generated by {insights.model}</p>
          </div>
        )}
      </div>
    </div>
  );
}

function SparkleMark() {
  return (
    <span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-emerald-400/10 text-emerald-400">
      <Lightbulb className="h-6 w-6" />
    </span>
  );
}
